[package]
name = "ows-runtime-dsl"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Parsing, serialization and validation of OWS workflow definitions"
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
ows-runtime-core = { path = "../ows-runtime-core" }
serverless_workflow_core = { workspace = true }
