//! Error types for the OWS runtime.
//!
//! OWS errors are described by the [Problem Details RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807).
//! This module defines the runtime's typed error surface while preserving the
//! structured, machine-readable shape required by the specification.

use std::fmt;

use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

/// The error categories required by the OWS compilation pipeline.
///
/// These categories must never be collapsed into a single generic error type.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ErrorKind {
    /// The input could not be decoded (malformed YAML / JSON, bad UTF-8, ...).
    Parse,
    /// The definition violates the OWS schema.
    Schema,
    /// The structure is syntactically valid but cannot be executed according to OWS semantics.
    Semantic,
    /// The workflow itself is valid but execution failed.
    Runtime,
    /// Evaluation of a runtime expression failed.
    Expression,
    /// A workflow or task timed out.
    Timeout,
    /// The workflow or task was cancelled.
    Cancelled,
    /// The workflow was faulted by an explicitly raised error.
    Fault,
    /// A runtime policy was violated (security / resource limits).
    Policy,
    /// An external service could not be reached or returned an invalid response.
    Communication,
}

impl ErrorKind {
    /// Returns a stable string tag for the kind.
    pub fn as_str(&self) -> &'static str {
        match self {
            ErrorKind::Parse => "parse",
            ErrorKind::Schema => "schema",
            ErrorKind::Semantic => "semantic",
            ErrorKind::Runtime => "runtime",
            ErrorKind::Expression => "expression",
            ErrorKind::Timeout => "timeout",
            ErrorKind::Cancelled => "cancelled",
            ErrorKind::Fault => "fault",
            ErrorKind::Policy => "policy",
            ErrorKind::Communication => "communication",
        }
    }
}

impl fmt::Display for ErrorKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Base URL prefix for OWS standard error types.
pub const ERROR_TYPE_PREFIX: &str = "https://open-workflow-specification.org/spec/1.0.0/errors";

/// The OWS standard error types.
///
/// See "Standard Error Types" in the DSL reference.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum StandardErrorType {
    Configuration,
    Validation,
    Expression,
    Authentication,
    Authorization,
    Timeout,
    Communication,
    Runtime,
}

impl StandardErrorType {
    /// The default HTTP status code associated with the error type.
    pub fn default_status(self) -> u16 {
        match self {
            StandardErrorType::Configuration => 400,
            StandardErrorType::Validation => 400,
            StandardErrorType::Expression => 400,
            StandardErrorType::Authentication => 401,
            StandardErrorType::Authorization => 403,
            StandardErrorType::Timeout => 408,
            StandardErrorType::Communication => 500,
            StandardErrorType::Runtime => 500,
        }
    }

    /// The error type URI.
    pub fn uri(self) -> String {
        let slug = match self {
            StandardErrorType::Configuration => "configuration",
            StandardErrorType::Validation => "validation",
            StandardErrorType::Expression => "expression",
            StandardErrorType::Authentication => "authentication",
            StandardErrorType::Authorization => "authorization",
            StandardErrorType::Timeout => "timeout",
            StandardErrorType::Communication => "communication",
            StandardErrorType::Runtime => "runtime",
        };
        format!("{ERROR_TYPE_PREFIX}/{slug}")
    }
}

/// A [Problem Details RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807) error.
///
/// This is the canonical error shape produced by the runtime and is preserved
/// verbatim when workflows fault.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProblemDetails {
    /// A URI reference that identifies the error type.
    #[serde(rename = "type")]
    pub type_: String,
    /// A short, human-readable summary of the problem.
    pub title: String,
    /// The HTTP status code generated by the origin for this occurrence.
    pub status: u16,
    /// A human-readable explanation specific to this occurrence.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    /// A JSON Pointer identifying the component the error originates from.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,
    /// Additional implementation specific members.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extensions: Option<Map<String, Value>>,
}

impl ProblemDetails {
    /// Creates a new problem details from parts.
    pub fn new(type_: impl Into<String>, title: impl Into<String>, status: u16) -> Self {
        Self {
            type_: type_.into(),
            title: title.into(),
            status,
            detail: None,
            instance: None,
            extensions: None,
        }
    }

    /// Sets the human readable detail.
    pub fn with_detail(mut self, detail: impl Into<String>) -> Self {
        self.detail = Some(detail.into());
        self
    }

    /// Sets the instance JSON pointer.
    pub fn with_instance(mut self, instance: impl Into<String>) -> Self {
        self.instance = Some(instance.into());
        self
    }

    /// Sets additional members.
    pub fn with_extension(mut self, key: impl Into<String>, value: Value) -> Self {
        let map = self.extensions.get_or_insert_with(Map::new);
        map.insert(key.into(), value);
        self
    }

    /// Creates a problem details from a standard error type.
    pub fn standard(kind: StandardErrorType) -> Self {
        Self::new(kind.uri(), kind.as_str(), kind.default_status())
    }

    /// Returns the error as a JSON value.
    pub fn to_value(&self) -> Value {
        serde_json::to_value(self).unwrap_or(Value::Null)
    }
}

impl StandardErrorType {
    fn as_str(self) -> &'static str {
        match self {
            StandardErrorType::Configuration => "Configuration",
            StandardErrorType::Validation => "Validation Error",
            StandardErrorType::Expression => "Expression Error",
            StandardErrorType::Authentication => "Authentication Error",
            StandardErrorType::Authorization => "Authorization Error",
            StandardErrorType::Timeout => "Timeout Error",
            StandardErrorType::Communication => "Communication Error",
            StandardErrorType::Runtime => "Runtime Error",
        }
    }
}

/// A structured workflow error.
///
/// This is the primary error type flowing through the runtime. It wraps a
/// [`ProblemDetails`] (the OWS-facing error) together with the internal error
/// category and, optionally, the original source error via [`std::error::Error::source`].
#[derive(Debug)]
pub struct WorkflowError {
    /// The error category.
    pub kind: ErrorKind,
    /// The OWS problem details describing the error.
    pub problem: ProblemDetails,
    /// The task reference, if the error originated from a task.
    pub task: Option<String>,
    /// The execution id, if available.
    pub execution_id: Option<String>,
    /// The source error, preserved.
    pub source: Option<Box<dyn std::error::Error + Send + Sync>>,
}

impl fmt::Display for WorkflowError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{} error (status {}): {}",
            self.kind, self.problem.status, self.problem.type_
        )
    }
}

impl std::error::Error for WorkflowError {}

impl Clone for WorkflowError {
    fn clone(&self) -> Self {
        Self {
            kind: self.kind,
            problem: self.problem.clone(),
            task: self.task.clone(),
            execution_id: self.execution_id.clone(),
            // The source is intentionally not cloned (boxed errors are not Clone).
            source: None,
        }
    }
}

impl WorkflowError {
    /// Creates a new workflow error.
    pub fn new(kind: ErrorKind, problem: ProblemDetails) -> Self {
        Self {
            kind,
            problem,
            task: None,
            execution_id: None,
            source: None,
        }
    }

    /// Creates a new workflow error from a standard error type.
    pub fn standard(kind: ErrorKind, standard: StandardErrorType) -> Self {
        Self::new(kind, ProblemDetails::standard(standard))
    }

    /// Attaches a task reference.
    pub fn with_task(mut self, task: impl Into<String>) -> Self {
        self.task = Some(task.into());
        self
    }

    /// Attaches an execution id.
    pub fn with_execution(mut self, execution_id: impl Into<String>) -> Self {
        self.execution_id = Some(execution_id.into());
        self
    }

    /// Attaches the source error.
    pub fn with_source<E>(mut self, source: E) -> Self
    where
        E: std::error::Error + Send + Sync + 'static,
    {
        self.source = Some(Box::new(source));
        self
    }

    /// Returns the problem details as a JSON value.
    pub fn to_problem_json(&self) -> Value {
        self.problem.to_value()
    }

    /// Convenience constructor for a timeout error.
    pub fn timeout(instance: Option<String>) -> Self {
        Self::new(
            ErrorKind::Timeout,
            ProblemDetails::standard(StandardErrorType::Timeout),
        )
        .map_instance(instance)
    }

    /// Convenience constructor for a cancellation error.
    pub fn cancelled() -> Self {
        let mut problem = ProblemDetails::standard(StandardErrorType::Runtime);
        problem.title = "Cancelled".to_string();
        problem.type_ = format!("{ERROR_TYPE_PREFIX}/runtime");
        Self::new(ErrorKind::Cancelled, problem)
    }

    fn map_instance(mut self, instance: Option<String>) -> Self {
        self.problem.instance = instance;
        self
    }
}

impl From<serde_json::Error> for WorkflowError {
    fn from(err: serde_json::Error) -> Self {
        let problem =
            ProblemDetails::standard(StandardErrorType::Runtime).with_detail(err.to_string());
        Self::new(ErrorKind::Parse, problem).with_source(err)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn error_kind_strings() {
        assert_eq!(ErrorKind::Parse.as_str(), "parse");
        assert_eq!(ErrorKind::Timeout.as_str(), "timeout");
        assert_eq!(ErrorKind::Cancelled.as_str(), "cancelled");
    }

    #[test]
    fn standard_error_types() {
        assert_eq!(
            StandardErrorType::Timeout.uri(),
            format!("{ERROR_TYPE_PREFIX}/timeout")
        );
        assert_eq!(StandardErrorType::Timeout.default_status(), 408);
        assert_eq!(StandardErrorType::Authorization.default_status(), 403);
        assert_eq!(StandardErrorType::Authentication.default_status(), 401);
        assert_eq!(StandardErrorType::Validation.default_status(), 400);
    }

    #[test]
    fn problem_details_builds() {
        let p = ProblemDetails::new("https://x/errors/e", "E", 500)
            .with_detail("detail")
            .with_instance("/do/0")
            .with_extension("k", serde_json::json!("v"));
        assert_eq!(p.status, 500);
        assert_eq!(p.detail.as_deref(), Some("detail"));
        let v = p.to_value();
        assert_eq!(v["type"], "https://x/errors/e");
        assert_eq!(v["extensions"]["k"], "v");
    }

    #[test]
    fn workflow_error_wraps_problem() {
        let err = WorkflowError::new(
            ErrorKind::Fault,
            ProblemDetails::standard(StandardErrorType::Runtime),
        )
        .with_task("/do/0/x")
        .with_execution("exec-1");
        assert_eq!(err.kind, ErrorKind::Fault);
        assert_eq!(err.task.as_deref(), Some("/do/0/x"));
        assert_eq!(err.execution_id.as_deref(), Some("exec-1"));
        assert_eq!(
            err.to_problem_json()["type"],
            StandardErrorType::Runtime.uri()
        );
    }

    #[test]
    fn timeout_and_cancelled_errors() {
        let t = WorkflowError::timeout(Some("/do/0".to_string()));
        assert_eq!(t.kind, ErrorKind::Timeout);
        assert_eq!(t.problem.status, 408);
        let c = WorkflowError::cancelled();
        assert_eq!(c.kind, ErrorKind::Cancelled);
    }

    #[test]
    fn workflow_error_clone_preserves_fields() {
        let err = WorkflowError::new(
            ErrorKind::Runtime,
            ProblemDetails::standard(StandardErrorType::Runtime),
        )
        .with_execution("e");
        let c = err.clone();
        assert_eq!(c.execution_id, err.execution_id);
        assert_eq!(c.problem, err.problem);
    }

    #[test]
    fn error_kind_display_all_variants() {
        for (kind, s) in [
            (ErrorKind::Parse, "parse"),
            (ErrorKind::Schema, "schema"),
            (ErrorKind::Semantic, "semantic"),
            (ErrorKind::Runtime, "runtime"),
            (ErrorKind::Expression, "expression"),
            (ErrorKind::Timeout, "timeout"),
            (ErrorKind::Cancelled, "cancelled"),
            (ErrorKind::Fault, "fault"),
            (ErrorKind::Policy, "policy"),
            (ErrorKind::Communication, "communication"),
        ] {
            assert_eq!(kind.to_string(), s);
            assert_eq!(kind.as_str(), s);
        }
    }

    #[test]
    fn standard_error_types_all() {
        for t in [
            StandardErrorType::Configuration,
            StandardErrorType::Validation,
            StandardErrorType::Expression,
            StandardErrorType::Authentication,
            StandardErrorType::Authorization,
            StandardErrorType::Timeout,
            StandardErrorType::Communication,
            StandardErrorType::Runtime,
        ] {
            assert!(t.uri().contains("/errors/"));
            assert!(t.default_status() >= 400);
            assert!(!ProblemDetails::standard(t).title.is_empty());
        }
    }

    #[test]
    fn workflow_error_standard_and_display() {
        let err = WorkflowError::standard(ErrorKind::Expression, StandardErrorType::Expression);
        assert_eq!(err.kind, ErrorKind::Expression);
        assert!(!err.to_string().is_empty());
    }

    #[test]
    fn from_json_error() {
        let e = serde_json::from_str::<serde_json::Value>("{").unwrap_err();
        let err = WorkflowError::from(e);
        assert_eq!(err.kind, ErrorKind::Parse);
    }
}
